name: Deploy on push

on:
  push:
    branches:
      - master

env:
  PM2_HOME: /opt/inz/.pm2/
  CLIENT_PORT: 3030
  CLIENT_DIST: /opt/inz/aghHoborski/client
  SERVER_PORT: 2020
  SERVER_DIST: /opt/inz/aghHoborski/server

jobs:
  setup-workspace:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  build-server:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Update packages
        run: |
          npm ci
          pm2 stop hoborski-server

      - name: Deploy server
        run: |
          rm -rf $SERVER_DIST
          cp -r ../server/ $SERVER_DIST
          pm2 start hoborski-server

  build-client:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build client
        run: |
          npm ci
          npm run build

      - name: Deploy client
        run: |
          rm -rf $CLIENT_DIST
          cp -r dist/ $CLIENT_DIST
