name: Server manual deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        default: master
        required: true
      tests:
        description: To run tests or not
        default: true
        required: true
      server-port:
        description: Port to start server
        default: 2222
        required: true

env:
  PM2_HOME: /opt/inz/.pm2/
  SERVER_DIST: /opt/inz/aghHoborski/server
  SERVER_PORT: ${{ github.event.inputs.server-port }}

jobs:
  setup-workspace:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout to specified branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Update dependencies
        run: |
          npm ci

  tests:
    needs: [setup-workspace]
    runs-on: self-hosted
    if: github.event.inputs.tests == 'true'
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run tests
        run: |
          npm run test

  build:
    needs: [setup-workspace, tests]
    runs-on: self-hosted
    if: ${{ always() }} # run build after tests but do not care about result
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build server
        run: |
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy server
        run: |
          pm2 stop hoborski-server
          rm -rf $SERVER_DIST/*
          cp -r ../server/{build,node_modules,public} $SERVER_DIST
          pm2 start hoborski-server --update-env
        env:
          NODE_ENV: production
