name: '[MAIN] Deploy on push'

on:
  push:
    branches:
      - master

env:
  PM2_HOME: /opt/inz/.pm2/
  CLIENT_DIST: /opt/inz/aghHoborski/client
  SERVER_DIST: /opt/inz/aghHoborski/server

jobs:
  setup-workspace:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  server-tests:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test

  build-server:
    needs: [setup-workspace, server-tests]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build server
        run: |
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy server
        run: |
          pm2 stop hoborski-server
          rm -rf $SERVER_DIST/*
          cp -r ../server/{build,node_modules,public} $SERVER_DIST
          pm2 start hoborski-server --update-env
        env:
          NODE_ENV: production

  build-client:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update dependencies
        run: |
          npm ci

      - name: Build client
        run: |
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy client
        run: |
          rm -rf $CLIENT_DIST
          cp -r dist/ $CLIENT_DIST
