name: Deploy on push

on:
  push:
    branches:
      - master

env:
  PM2_HOME: /opt/inz/.pm2/
  NODE_ENV: production
  # CLIENT_PORT: 3333
  SERVER_PORT: 2222

jobs:
  setup-workspace:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: /opt/inz/aghHoborski
        # not pulling correctly repository

  build-server:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /opt/inz/aghHoborski/server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Update packages
        run: |
          npm ci

      - name: Run server
        run: |
          pm2 restart hoborski-server

  build-client:
    needs: [build-server]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /opt/inz/aghHoborski/client

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Update packages
        run: |
          npm ci

      - name: Build client
        run: |
          npm run build
