name: '[MAIN] Deploy on push'

on:
  push:
    branches:
      - master

env:
  PM2_HOME: /opt/inz/.pm2/
  CLIENT_DIST: /opt/inz/aghHoborski/client
  SERVER_DIST: /opt/inz/aghHoborski/server

jobs:
  setup-workspace:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  build-server:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: server

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build server
        run: |
          npm ci
          npm run build

      - name: Deploy server
        run: |
          pm2 stop hoborski-server
          rm -rf $SERVER_DIST/*
          cp -r ../server/{build,node_modules,public} $SERVER_DIST
          pm2 start hoborski-server --update-env
        env:
          NODE_ENV: production

  build-client:
    needs: [setup-workspace]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build client
        run: |
          npm ci
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy client
        run: |
          rm -rf $CLIENT_DIST
          cp -r dist/ $CLIENT_DIST
